# Generated by Django 3.1.7 on 2021-03-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210309_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='この項目は必須です。メールアドレスは公開されません。', max_length=254, verbose_name='メールアドレス'),
        ),
    ]
