# Generated by Django 3.1.7 on 2021-03-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name='学科名'),
        ),
    ]
