# Generated by Django 3.1.7 on 2021-03-11 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_auto_20210309_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='学科名'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(max_length=30, null=True, verbose_name='学籍番号'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='thread.category', verbose_name='学科名'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='message',
            field=models.TextField(null=True, verbose_name='講義情報'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=255, verbose_name='講義名'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user_name',
            field=models.CharField(max_length=30, null=True, verbose_name='学籍番号'),
        ),
    ]
